// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xr.User.Infrastructure;

#nullable disable

namespace Xr.User.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Xr.User.Domain.Domain.UserOauth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GmtCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GmtModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Modifier")
                        .HasColumnType("bigint");

                    b.Property<int>("Plateform")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("ValueId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserOauth");
                });

            modelBuilder.Entity("Xr.User.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime")
                        .HasColumnName("birthday");

                    b.Property<long>("Creator")
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("creator");

                    b.Property<DateTime>("GmtCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("gmt_created");

                    b.Property<DateTime>("GmtModified")
                        .HasColumnType("datetime")
                        .HasColumnName("gmt_modified");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id_no");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_deleted");

                    b.Property<sbyte>("IsReal")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_real");

                    b.Property<long>("Modifier")
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("modifier");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nick_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("real_name");

                    b.Property<sbyte>("Sex")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("sex");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Xr.User.Domain.UserFollow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Creator")
                        .HasColumnType("BIGINT(20)")
                        .HasColumnName("creator");

                    b.Property<DateTime>("FollowTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("follow_time");

                    b.Property<DateTime>("GmtCreated")
                        .HasColumnType("DATETIME")
                        .HasColumnName("gmt_created");

                    b.Property<DateTime>("GmtModified")
                        .HasColumnType("DATETIME")
                        .HasColumnName("gmt_modified");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnType("TINYINT")
                        .HasColumnName("is_deleted");

                    b.Property<long>("Modifier")
                        .HasColumnType("BIGINT(20)")
                        .HasColumnName("modifier");

                    b.Property<sbyte>("Status")
                        .HasColumnType("TINYINT(4)")
                        .HasColumnName("status");

                    b.Property<sbyte>("Type")
                        .HasColumnType("TINYINT(4)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("BIGINT(20)")
                        .HasColumnName("user_id");

                    b.Property<long>("ValueId")
                        .HasColumnType("BIGINT(20)")
                        .HasColumnName("value_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_follow", (string)null);
                });

            modelBuilder.Entity("Xr.User.Domain.UserServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Creator")
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("creator");

                    b.Property<DateTime>("GmtCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("gmt_created");

                    b.Property<DateTime>("GmtModified")
                        .HasColumnType("datetime")
                        .HasColumnName("gmt_modified");

                    b.Property<sbyte>("IsAudit")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_audit");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_deleted");

                    b.Property<long>("Modifier")
                        .HasMaxLength(20)
                        .HasColumnType("bigint(20)")
                        .HasColumnName("modifier");

                    b.Property<float>("RatePoint")
                        .HasColumnType("float(11,2)")
                        .HasColumnName("rate_point");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_server", (string)null);
                });

            modelBuilder.Entity("Xr.User.Domain.Domain.UserOauth", b =>
                {
                    b.HasOne("Xr.User.Domain.User", "User")
                        .WithMany("UserOauths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Xr.User.Domain.UserFollow", b =>
                {
                    b.HasOne("Xr.User.Domain.User", "User")
                        .WithMany("UserFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Xr.User.Domain.UserServer", b =>
                {
                    b.HasOne("Xr.User.Domain.User", "User")
                        .WithOne("UserServer")
                        .HasForeignKey("Xr.User.Domain.UserServer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Xr.User.Domain.User", b =>
                {
                    b.Navigation("UserFollows");

                    b.Navigation("UserOauths");

                    b.Navigation("UserServer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
