<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="MessageConsumer\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xr.User.Domain\Xr.User.Domain.csproj" />
    <ProjectReference Include="..\Xr.User.Infrastructure\Xr.User.Infrastructure.csproj" />
  </ItemGroup>

</Project>
