<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Aspros.Base.Framework.Domain" Version="1.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="DomainEvent\EventHandler\" />
	</ItemGroup>

</Project>
